### ISSUE TITLE
Need a `get-receiver` incoming binding operator?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/webidl-bindings#45]
Say I have this Web IDL interface:

```webidl
interface Foo {
    void myMethod();
}
```

And I am implementing `my_method` in Wasm with the following function:

```wasm
(func $myMethod (param anyref)
  ;; ...
  )
```

For the bindings between `Foo#myMethod` and `$myMethod`, we need an incoming binding expression similar to `get`, but which gets the `this` receiver rather than an indexed parameter.

Note that this need comes up not just for methods on interfaces, but also for various callbacks on the Web where `this` is used to pass extra contextual information (e.g. event listeners).

Or alternatively, is the `this` receiver intended to always the first element of the incoming Web IDL values? If so, then we should make this more clear and provide an example of using the `this` receiver from Wasm.

**Comment by lukewagner** [comment]
This isn't super-clearly documented, but the idea, [in the explainer](https://github.com/WebAssembly/webidl-bindings/blob/master/proposals/webidl-bindings/Explainer.md#function-bindings), is if the function is declared to be a "method" (via `(method any)`), then the receiver is taken/provided as the first argument.

**Comment by fitzgen** [comment]
Ah yeah, I missed that when looking at the explainer again. I think clarifying this further is unnecessary for the explainer, and should instead be in the actual standard, so I'm going to close this issue.
